import os
from dotenv import load_dotenv

load_dotenv()

DATABASE_URL = os.getenv("DATABASE_URL")
SECRET_KEY = os.getenv("SECRET_KEY")
ACCESS_TOKEN_EXPIRE_MINUTES = os.getenv("ACCESS_TOKEN_EXPIRE_MINUTES")
ALGORITHM = os.getenv("ALGORITHM")
RESEND_API_KEY = os.getenv('RESEND_API_KEY')
GENERATE_QR_URL = os.getenv('PAYMONGO_QR_GENERATE_URL')


PAYMENT_SECRET_KEY = os.getenv('PAYMENT_SECRET_KEY') #live key
PAYMONGO_SECRET_KEY = os.getenv('PAYMONGO_SECRET_KEY') #test key

PAYMONGO_BASE_URL = os.getenv('PAYMONGO_BASE_URL')
FRONTEND_URL = os.getenv('FRONTEND_URL')

VERIFICATION_TOKEN_EXPIRE_MINUTES = os.getenv('VERIFICATION_TOKEN_EXPIRE_MINUTES')